### ISSUE TITLE
Installation via Ressource Sharing pluging won't work on windows 10

### ISSUE THREAD

**Issue by MarHoff** [gacarrillor/QGIS-Resources#1]
I managed to install the extension via the Ressource Sharing plugin. The file appear on disk inside the following folder:
Processing Scripts (PyQGIS) by Germán Carrillo (57fa38b8a8b584ade39d9cd2f098ead610f68796)

However it don't show up neither in the "Instaled" tab of Resource Sharing, nor in the processing toolbox.
Adding the file manually is working and the script seems to work like a breeze at my frist test. Kudo!

I suspect it might work better if you removed the special accent here too, but I'm not familiar with the Ressource Sharing Plugin so I might be wrong.
https://github.com/gacarrillor/QGIS-Resources/blob/master/metadata.ini#L7

Env : QGIS version 2.16.2, Windows 10

**Comment by gacarrillor** [comment]
Thanks for the feedback @MarHoff. 
Strange, on a GNU/Linux machine there are no issues with the accent.

I've removed the accent from the line you mentioned. 
Please give it a second try (please first uninstall/remove all files created by the QGIS Resource Sharing Plugin when installing my resources) and let me know if it solves the problem, so that we can close this issue.

**Comment by MarHoff** [comment]
Hello, I'll try on Monday at work and let you know asap!
Thanks!

**Comment by MarHoff** [comment]
Hello still don't work :/ Must be something else...

I got the "Successfully installed" prompt, but your libraries don't show up in installed tab. Maybe it comme from the round bracket () around PyQGIS because it seems that RessourceSharing us them in folder name to store a token.
 Processing Scripts (PyQGIS) by Germán Carrillo (_**57fa38b8a8b584ade39d9cd2f098ead610f68796**_)

I'll try with a fork so you don't spoil your master with theses tests.

**Comment by MarHoff** [comment]
After a few test I drove my QGIS installation into an unstable state. I can't say exactly what caused that and I really can't exclude that this bug was caused by corrupted user setting (mine have been updated since QGIS 2.6)

Anyway nuking all users setting set everything back in order.
Path on win10 : C:\Users\USERNAME.qgis2

Everything with your install now work just as expected. Thanks for taking time on my issue!

**Comment by gacarrillor** [comment]
Great, thanks for the feedback! 
Summarizing, I'll avoid using accents in metadata.ini anyway. I wasn't aware of QGIS Resource Sharing using that value as folder name.

**Comment by havatv** [comment]
Since version 0.12.0, the QGIS Resource Sharing plugin does not use collection names as directory/folder names. It should therefore be safe to use both non-ASCII characters and characters that are not allowed in Windows directory and file names.
