### ISSUE TITLE
Do you plan to update for QGIS3 ?

### ISSUE THREAD

**Issue by MarHoff** [gacarrillor/QGIS-Resources#2]
Hello, it's your distant fan again

I find this script of your very useful "Export_Composers_of_Multiple_Projects.py" so no matter what, thanks again for this gift.

I understand however that it's hassle to maintain an that's why I wouldn't even dare to ask before both MapPrinter and QGIS-Ressources sharing plugins were ported to QGIS3. Which is the case as of today.

Have you any plans on updating scripts and repo?

Best regards

**Comment by gacarrillor** [comment]
Hi @MarHoff!

jeje, great! Now that you mention, yes, it makes sense. I'll see when I can make some time for this and let you know. 

Have a nice weekend!

**Comment by peterbishop88** [comment]
Hi @gacarrillor ! 

This script is fantastic, but I agree - an update for QGIS would be amazing :D 

@MarHoff - have you found any other solutions for QGIS3 yet?

**Comment by MarHoff** [comment]
Hi sorry didn't have time to investigate. and unfortunatelly I'm really not a python person :(

But I'll start working on the documents collection than now need to be upgraded to QGIS 3.4 in the coming month.

I personally see a big potential for script like this one now that you can even load QGIS3 documents stored in PostgreSQL. But I guess supporting that new feature would involve even more work than just supporting folder selection...

**Comment by peterbishop88** [comment]
Thanks for the reply! Yes, there is a lot of potential for this script. I
agree, a good first step would be to keep the current workflow with the
folder selection.

**Comment by gacarrillor** [comment]
Hey @MarHoff and @peterbishop88,

today I could make some time for updating the script. If you can test it and let me know if everything goes well, it would be awesome: 

https://github.com/gacarrillor/QGIS-Resources/blob/migrate_to_qgis3/collections/processing_scripts/processing/Export_Composers_of_Multiple_Projects.py

I haven't migrated the whole project to make it accessible from `QGIS Resource Sharing` plugin, so the only way to use the script for now is to copy the code and create a new script in the Processing toolbox.

Regards, 

Germán

**Comment by MarHoff** [comment]
Hello and thanks for the update.

I quickly ran it on Window10 with QGIS 3.4 and it seemed to work pretty well and (even against legacy 2.18 qgis projects).

Unfortunately I can't do more extended testing right now but I'll keep in touch if I notice anything out of place when I'll start working my relevant use case of you scripts in coming weeks.

Also I don't know how you'd feel about that but contributing this script into [MapsPrinter repository](https://github.com/DelazJ/MapsPrinter) could be a way to make this code more widely available. (I feel like QGIS-Ressource sharing is more widely used now for style sharing and that people rely more on extensions when looking for functionalities).

But I understand that MapsPrinter strangely don't have a licence file in the repo and that might be a no go. The author is french and work in a public administration just like me so let me now if I can be of any help on that.

Anyway thanks again a lot for the great work!

**Comment by gacarrillor** [comment]
Yes I also have the impression that QGIS Resource Sharing is more for styles. 

I can ask @DelazJ if he's interested in accepting this as a contribution: a new processing algorithm that will be installed once his plugin is installed. Good idea!

Just out of curiosity, in which city do you both work? I'll be in Europe in a few weeks, will you attend the FOSS4G in Bucharest?

**Comment by DelazJ** [comment]
Hi,
> Yes I also have the impression that QGIS Resource Sharing is more for styles.

It shouldn't.
> But I understand that MapsPrinter strangely don't have a licence file in the repo and that might be a no go. The author is french and work in a public administration just like me so let me now if I can be of any help on that.

hmmm. I simply used the plugin builder at that time and did never think about Licensing. Anyway I added it now, fwiw.
> I can ask @DelazJ if he's interested in accepting this as a contribution: a new processing algorithm that will be installed once his plugin is installed. Good idea!

Sure! If you think it makes sense! Note that I'm not a python developer and have recently spent less time than I wish on this (spare time) plugin. But i'll do my best (or i can grant you rights, if you want). 
Btw, from what I understand, that would fix https://github.com/DelazJ/MapsPrinter/issues/1. Right?

**Comment by gacarrillor** [comment]
Right @DelazJ, it would solve that issue!

The plan is to install a Processing algorithm along with your plugin. So if users want to batch export composers from projects in the same folder, they would use a GUI like this: 

![image](https://user-images.githubusercontent.com/652785/62734824-7f905b00-b9ef-11e9-9e34-339a44c2ab53.png)

![image](https://user-images.githubusercontent.com/652785/62734891-a484ce00-b9ef-11e9-9b59-8a8b2780017b.png)

**Comment by peterbishop88** [comment]
@gacarrillor Thank you so much! This is amazing. This saves me SO much time. It is also super easy to use. Thanks again!

**Comment by DelazJ** [comment]
Hi Germán
Discussion on the dev-list made me realize I did not reply to you. The plan looks good to me! Thanks

**Comment by gacarrillor** [comment]
@DelazJ, I just created a PR (https://github.com/DelazJ/MapsPrinter/pull/16) in Maps Printer repo. Let me know if you have any feedback :+1:

**Comment by gacarrillor** [comment]
Hi @MarHoff and @DelazJ, just wanted to ask you whether you want to meet with me someday in the next weeks. I'll be on holidays until mid January in France and I'm sure I could spend a day or a morning/afternoon with QGIS people there.
